version: "2.2"
services:
  site:
    image: jekyll/jekyll:latest
    command: jekyll serve --host 0.0.0.0 --incremental
    working_dir: /srv/jekyll
    ports:
      - "4000:4000"
    environment:
      #- "JEKYLL_ENV=production"
      - PAGES_REPO_NWO=Koenkk/zigbee2mqtt.io
    volumes:
      - ./docs:/srv/jekyll
      - ./.bundle:/usr/local/bundle
